"""replace category with features column

Revision ID: ac24ee03295f
Revises: fcf750372a85
Create Date: 2025-09-20 18:39:49.273442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac24ee03295f'
down_revision = 'fcf750372a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_model', sa.Column('features', sa.Text(), nullable=False, server_default=""))
    op.drop_column('image_model', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_model', sa.Column('category', sa.VARCHAR(length=50), nullable=False))
    op.drop_column('image_model', 'features')
    # ### end Alembic commands ###
